version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    env_file: .env
    ports:
      - "8000:8000"                # Expose FastAPI app on port 
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
    networks:
      - backend
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

networks:
  backend:
    driver: bridge
